# -*- coding: utf-8 -*-
"""final productipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qRAEWLBhF7oA0dPDAtjUhBXfUX5WJVeR
"""

import random

def get_difficulty():
    print("Please select the difficulty level:")
    print("1 - Easy (10 chances)")
    print("2 - Medium (5 chances)")
    print("3 - Hard (3 chances)")

# while True:
    choice = input("Enter your choice (1, 2, or 3): ")
    if choice == '1':
        return 10
    elif choice == '2':
        return 5
    elif choice == '3':
        return 3
    else:
        print("Invalid choice. Please enter 1, 2, or 3.")


def guessing_game():
    print("Welcome to the Guessing Game Plus!")
    print("I have selected a number between 1 and 100. Can you guess what it is?")
    secret_number = random.randint(1, 100)
    attempts_allowed = get_difficulty()
    print(f"\nGreat! You have selected the difficulty level with {attempts_allowed} chances.")

    attempts = 0

    while attempts < attempts_allowed:
        guess = int(input("Enter your guess: "))
        attempts += 1

        if guess < 1 or guess > 100:
            print("Please enter a number between 1 and 100.")
        elif guess < secret_number:
            print("Too low! Try again.")
        elif guess > secret_number:

            print("Too high! Try again.")
        else:
            print(f"Congratulations! You guessed the correct number in {attempts} attempts.")
            break
    else:
        print(f"Sorry, you've run out of chances. The correct number was {secret_number}.")

guessing_game()

